"""add grammar example translation and furigana

Revision ID: 11f51236688d
Revises: e4f543cd0d23
Create Date: 2026-09-14 17:24:37.216544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f51236688d'
down_revision: Union[str, Sequence[str], None] = 'e4f543cd0d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grammar_patterns', sa.Column('example_sentence_en', sa.Text(), nullable=True))
    op.add_column('grammar_patterns', sa.Column('example_sentence_furigana', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grammar_patterns', 'example_sentence_furigana')
    op.drop_column('grammar_patterns', 'example_sentence_en')
    # ### end Alembic commands ###
