"""add learning_session payload json column

Revision ID: 31c4eb9e577a
Revises: f5f95a7a2ff7
Create Date: 2026-09-16 00:42:35.012873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c4eb9e577a'
down_revision: Union[str, Sequence[str], None] = 'f5f95a7a2ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'payload')
    # ### end Alembic commands ###
