"""add repetitions to user_card_progress

Revision ID: 3b08f7e5a9f1
Revises: cb1ef0e632f4
Create Date: 2026-06-25 15:47:16.829956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b08f7e5a9f1'
down_revision: Union[str, Sequence[str], None] = 'cb1ef0e632f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_progress', sa.Column('repetitions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card_progress', 'repetitions')
    # ### end Alembic commands ###
