"""add writing characters, vocab links, grammar patterns

Revision ID: 4cd0f6cf8165
Revises: d9fdf0304bfd
Create Date: 2026-06-23 16:12:41.905900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd0f6cf8165'
down_revision: Union[str, Sequence[str], None] = 'd9fdf0304bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_patterns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('drill_sentence', sa.Text(), nullable=True),
    sa.Column('jlpt_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_characters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('character_type', sa.String(), nullable=False),
    sa.Column('romaji', sa.String(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('onyomi', sa.JSON(), nullable=True),
    sa.Column('kunyomi', sa.JSON(), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=False),
    sa.Column('stroke_paths', sa.JSON(), nullable=False),
    sa.Column('jlpt_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_characters_character'), 'writing_characters', ['character'], unique=False)
    op.create_table('vocab_character_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vocab_card_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('character_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['writing_characters.id'], ),
    sa.ForeignKeyConstraint(['vocab_card_id'], ['vocab_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_character_links')
    op.drop_index(op.f('ix_writing_characters_character'), table_name='writing_characters')
    op.drop_table('writing_characters')
    op.drop_table('grammar_patterns')
    # ### end Alembic commands ###
