"""add user name and avatar

Revision ID: 95d5d0b510ea
Revises: 0b231c24b5aa
Create Date: 2026-09-17 01:28:28.713293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d5d0b510ea'
down_revision: Union[str, Sequence[str], None] = '0b231c24b5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=False, server_default='cat'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
