"""add topic column to writing_characters

Revision ID: bd24e549b289
Revises: deada523edc5
Create Date: 2026-09-13 22:47:58.004711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd24e549b289'
down_revision: Union[str, Sequence[str], None] = 'deada523edc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_characters', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writing_characters', 'topic')
    # ### end Alembic commands ###
