"""rename module_type to content_type, add user_card_progress

Revision ID: cb1ef0e632f4
Revises: 4cd0f6cf8165
Create Date: 2026-06-25 15:16:04.161426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1ef0e632f4'
down_revision: Union[str, Sequence[str], None] = '4cd0f6cf8165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_card_progress',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('session_items', 'module_type', new_column_name='content_type')
    op.alter_column('user_mistakes', 'module_type', new_column_name='content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_mistakes', 'content_type', new_column_name='module_type')
    op.alter_column('session_items', 'content_type', new_column_name='module_type')
    op.drop_table('user_card_progress')
    # ### end Alembic commands ###
