"""add vocab_card source and agent_log retry columns

Revision ID: deada523edc5
Revises: 3b08f7e5a9f1
Create Date: 2026-09-12 16:58:44.057445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deada523edc5'
down_revision: Union[str, Sequence[str], None] = '3b08f7e5a9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_logs', sa.Column('tool_name', sa.String(), nullable=True))
    op.add_column('agent_logs', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('agent_logs', sa.Column('fallback_used', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('agent_logs', sa.Column('error_detail', sa.Text(), nullable=True))
    op.add_column('vocab_cards', sa.Column('source', sa.String(), nullable=False, server_default='seeded'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_cards', 'source')
    op.drop_column('agent_logs', 'error_detail')
    op.drop_column('agent_logs', 'fallback_used')
    op.drop_column('agent_logs', 'success')
    op.drop_column('agent_logs', 'tool_name')
    # ### end Alembic commands ###
