"""add vocab example translation and furigana

Revision ID: e4f543cd0d23
Revises: 45b6790decbc
Create Date: 2026-09-14 15:55:33.122758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f543cd0d23'
down_revision: Union[str, Sequence[str], None] = '45b6790decbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_cards', sa.Column('example_sentence_en', sa.Text(), nullable=True))
    op.add_column('vocab_cards', sa.Column('example_sentence_furigana', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_cards', 'example_sentence_furigana')
    op.drop_column('vocab_cards', 'example_sentence_en')
    # ### end Alembic commands ###
