"""add user session item count and session reasoning

Revision ID: f5f95a7a2ff7
Revises: c6abc5738cdd
Create Date: 2026-09-15 22:56:28.021839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f95a7a2ff7'
down_revision: Union[str, Sequence[str], None] = 'c6abc5738cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column(
        'users',
        sa.Column('session_item_count', sa.Integer(), nullable=False, server_default='10'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_item_count')
    op.drop_column('learning_sessions', 'reasoning')
    # ### end Alembic commands ###
